name: 自动发布到服务器

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取分支
        uses: actions/checkout@master

      - name: 搭建 Node 环境
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 10.15.3

      - name: 安装依赖-测试-打包
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: ssh deploy 服务器
        uses: easingthemes/ssh-deploy@v2.1.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET }}
          SOURCE: 'dist/'
          ARGS: '-avz --delete'
      
      - name: Dingtalk Webhook
        uses: ghostoy/dingtalk-action@v1.0.0
        with:
          # dingtalk webhook
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          # dingtalk message type
          msgtype: 'actionCard'
          # content for dingtalk message in JSON format
          content: '{"title": "部署成功通知", "text": "![img](https://avatars1.githubusercontent.com/u/19390881?s=460&u=e7b424845efe334d6ce584f9af6221aa6eb8c9a0&v=4) \n\n仓库: [${{ github.repository }}](https://github.com/${{ github.repository }}) \n\n操作: ${{ github.actor }} 进行了 ${{ github.event_name }} \n\n操作对象:  ${{  github.ref	}} \n\n线上地址: [点击访问](http://jaytan.club/) ", "btnOrientation": "0", "btns": [{"title": "查看项目", "actionURL": "http://jaytan.club/"}]}'
          # secret used for signing
          secret: ${{ secrets.DINGTALK_SECRET }}
